# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.IntegerField(default=0)),
                ('alert_description', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_first_name', models.CharField(default='', max_length=256)),
                ('doctor_last_name', models.CharField(default='', max_length=256)),
                ('doctor_user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_notes', models.TextField(default='Insert Notes For Lab Test')),
                ('lab_systolic_blood_pressure', models.IntegerField(default=120)),
                ('lab_CHF', models.CharField(choices=[('No CHF', 'No CHF'), ('Rales and/or JVD', 'Rales and/or JVD'), ('Pulmonary edema', 'Pulmonary edema'), ('Cardiogenic shock', 'Cardiogenic shock')], default='No CHF', max_length=256)),
                ('lab_creatinine', models.DecimalField(decimal_places=5, default=0.5, max_digits=5)),
                ('lab_cardiac_arrest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=256)),
                ('lab_biomarkers', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=256)),
                ('lab_st_elev', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LabTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_first_name', models.CharField(default='', max_length=256)),
                ('lab_last_name', models.CharField(default='', max_length=256)),
                ('lab_user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.IntegerField(default=0)),
                ('alertSent', models.IntegerField(default=0)),
                ('date_created', models.CharField(default='11-3-2018', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('nurse', 'nurse'), ('staff', 'staff'), ('doctor', 'doctor'), ('patient', 'patient'), ('lab', 'lab')], max_length=256)),
                ('user', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempPatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=256)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer not to say', 'Prefer Not To Say')], default='Select a gender', max_length=256)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128)),
                ('DOB', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=256)),
                ('heart_rate', models.IntegerField(default=72)),
                ('systolic_blood_pressure', models.IntegerField(default=120)),
                ('CHF', models.CharField(choices=[('No CHF', 'No CHF'), ('Rales and/or JVD', 'Rales and/or JVD'), ('Pulmonary edema', 'Pulmonary edema'), ('Cardiogenic shock', 'Cardiogenic shock')], default='No CHF', max_length=256)),
                ('creatinine', models.DecimalField(decimal_places=5, default=0.5, max_digits=5)),
                ('cardiac_arrest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=256)),
                ('biomarkers', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=256)),
                ('st_elev', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=256)),
                ('data_sent', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='fill_from_application',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='acs.TempPatientData'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreport',
            name='lab_patient',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='acs.Patient'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='lab_tech',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='acs.LabTech'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='acs.Patient'),
        ),
    ]
