# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_auto_20180313_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='lab_CHF',
            new_name='CHF',
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='lab_biomarkers',
            new_name='biomarkers',
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='lab_cardiac_arrest',
            new_name='cardiac_arrest',
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='lab_creatinine',
            new_name='creatinine',
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='lab_st_elev',
            new_name='st_elev',
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='lab_systolic_blood_pressure',
            new_name='systolic_blood_pressure',
        ),
    ]
