# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0004_auto_20180330_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='acs.Doctor')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='acs.Patient')),
            ],
        ),
    ]
